ALTER TABLE tasks ADD COLUMN description TEXT;
ALTER TABLE tasks ADD COLUMN priority VARCHAR(20);
ALTER TABLE tasks ADD COLUMN assignee VARCHAR(100);
ALTER TABLE tasks ADD COLUMN due_date TIMESTAMP;
ALTER TABLE tasks ADD COLUMN issue_type VARCHAR(50);
